### ISSUE TITLE
Sonderzeichen in der Straße werden nicht richtig angezeigt

### ISSUE THREAD

**Issue by CapOfCave** [HSWsac2/depot-ui#6]
vermutlich liegt das Problem im Backend, sollte aber geprüft werden. Evtl. Issue einstellen

**Comment by Sparkobbable** [comment]
Das liegt am Backend

**Comment by Sparkobbable** [comment]
Bezieht sich übrigens auf generell alle Sonderzeichen aus dem Backend, bug ist im Board der backend gruppe eingestellt

**Comment by CapOfCave** [comment]
Sollte behoben sein
